### ISSUE TITLE
Screen goes black after setting tabbar item badge to nil

### ISSUE THREAD

**Issue by UtkuDalmaz** [namshi/NMAnimatedTabBarItem#2] opened 2018-08-17 11:18 UTC
```
let tabArray = self.tabBarController?.tabBar.items as NSArray?
let tabItem = tabArray?.object(at: 4) as! UITabBarItem
tabItem.badgeValue = nil
```

This code **sometimes** makes app goes black screen.

**Comment by BaluNaik** [comment] 2018-08-19 06:58
@UtkuDalmaz Not able to reproduce.
 If your controller is a subclass of `UITabBarController` try this

```
let tabArray = self.tabBar.items
let tabItem = tabArray![4]
tabItem.badgeValue = nil
```

**Comment by BaluNaik** [comment] 2018-11-28 10:39
No repose, so closing issue.

**Closed as completed by BaluNaik** 2018-11-28 10:39 UTC
